export const projectsData = [
  {
    id: "careerpulse-ai",
    title: "CareerPulse AI",
    description: "An AI-powered resume analyzer and interview coach designed to help candidates prepare for their dream jobs.",
    fullDescription: "CareerPulse AI uses advanced natural language processing to analyze resumes against job descriptions, providing actionable feedback. It also includes an interactive interview simulation module where users can practice answering technical and behavioral questions in a realistic environment.",
    image: "https://picsum.photos/seed/careerpulse/1200/800",
    technologies: ["Next.js", "React", "Tailwind CSS", "OpenAI API", "PostgreSQL"],
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: "smarthome-guardian",
    title: "SmartHome_Guardian",
    description: "A smart home mobile application providing real-time monitoring and control of IoT devices securely.",
    fullDescription: "SmartHome_Guardian provides a unified interface for controlling diverse IoT devices. It features real-time monitoring, customizable automation routines, and robust end-to-end encryption to ensure user privacy and security across all connected home devices.",
    image: "https://picsum.photos/seed/smarthome/1200/800",
    technologies: ["React Native", "Expo", "Firebase", "Node.js", "IoT Protocols"],
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: "digital-healthcare-web-platform",
    title: "Digital Healthcare Web Platform",
    description: "A full-stack healthcare solution for managing patient records, appointments, and telemedicine consultations.",
    fullDescription: "This comprehensive platform streamlines healthcare operations. Patients can securely access their medical records, book appointments, and attend virtual consultations via WebRTC, while doctors can easily manage their schedules and patient notes.",
    image: "https://picsum.photos/seed/healthcare/1200/800",
    technologies: ["Next.js", "TypeScript", "Prisma", "WebRTC", "Stripe"],
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: "market-analyzer",
    title: "Market Analyzer",
    description: "A robust data analysis tool for tracking market trends, visualizing financial data, and generating insights.",
    fullDescription: "Market Analyzer aggregates financial data from multiple APIs, processing it to generate real-time charts and predictive insights. It supports custom dashboards and alerts for specific market movements to empower informed trading decisions.",
    image: "https://picsum.photos/seed/market/1200/800",
    technologies: ["React", "D3.js", "Python", "FastAPI", "Redis"],
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: "event-ledger",
    title: "Event Ledger",
    description: "An application for tracking and managing events, ticketing, and attendee interactions with a seamless UI.",
    fullDescription: "Event Ledger simplifies event management from creation to post-event analytics. Organizers can create customizable ticketing pages, while attendees enjoy a seamless checkout experience and QR code generation for streamlined entry.",
    image: "https://picsum.photos/seed/event/1200/800",
    technologies: ["Next.js", "Tailwind CSS", "PostgreSQL", "Supabase"],
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: "smartengineeringcm",
    title: "smartengineeringcm",
    description: "A complete portfolio website built for a client to showcase their engineering services and projects.",
    fullDescription: "A tailored portfolio platform designed to highlight the client's engineering expertise. Features a dynamic CMS for easily updating case studies, high-resolution image galleries, and contact lead generation integrations.",
    image: "https://picsum.photos/seed/smartengineering/1200/800",
    technologies: ["Next.js", "Framer Motion", "Tailwind CSS", "Sanity CMS"],
    demoLink: "#",
    githubLink: "#",
  },
];
